---
title: "About"
site: distill::distill_website
---
Hello! My name is Grant Li. My Chinese name is 李元. I'm a student at Northwestern University studying English literature and political science, with a minor in data science. I am also in the Northwestern University Marching Band (NUMB), Basketball Band, and Purple Band, which is a paid 29-piece ensemble that the athletic department arranges to perform at non-revenue sports events. Additionally, I work in the Art Library and I'm a Farrell Fellow with the Deportation Research Clinic here at Northwestern.

A FOIA data dashboard I built: https://grantli.shinyapps.io/foiaapp/

I am also the Assistant Opinion Editor and an opinion columnist at the Daily Northwestern. You can find my writing here: https://dailynorthwestern.com/staff_name/grant-li/#

I like to read, although I don't read as many books as I should. Instead, I end up reading a lot of articles. You can see what I read on my Curius profile: https://curius.app/grant-li  

When I actually do read books, you can find them on my goodreads: https://www.goodreads.com/user/show/103275829-grant-li

Here is my resume: https://tinyurl.com/ma7zck65

I also like art (hence the pun in the url), classical music, and the Utah Jazz.